adding return type to methods
negue/meme-box pull request #350
Opened 2021-10-24 10:32 UTC by chiragmahawar7

2021-10-26 15:08 UTC, negue requested changes
LGTM , only 2 comments / changes but then this could be merged in. 👍

2021-10-26 15:08 UTC, negue commented on src/app/manage/media/media-overview/media-card/media-card.component.ts
> +    if (this.media === null || this.media.tags === null || tagssEmpty) {
I think on this line it could be just written as `!this.media?.tags` incase `this.media.tags` is not a null but undefined - then the triple check would say false

2021-10-26 15:08 UTC, negue commented on src/app/shared/dialogs/screen-arrange/drag-resize-media/drag-resize-media.component.ts
> +    while (m == cssTransformRegex.exec(nativeElement.style.transform)) {
this needs to be reverted.  with your change it would never have any values, since m is null 2 lines above

But looking at that it is really weird :D , could you add a comment above it => `// TODO REFACTOR` 

I think need to redo this completely and I even wonder how this worked at all 😁

2021-10-29 13:13 UTC, chiragmahawar7 commented
> LGTM , only 2 comments / changes but then this could be merged in. 👍

I have updated the PR

2021-10-29 14:11 UTC, negue commented
Thank you for the contributions! 

Would you like also to get added to the contributors list? :)

2021-10-29 14:11 UTC, merged

2021-10-30 08:35 UTC, chiragmahawar7 commented
> Thank you for the contributions!
> 
> Would you like also to get added to the contributors list? :)

Yeah sure.
I would try to look into more issues & enhancements.

2021-10-30 12:20 UTC, negue commented
Awesome! There is a lot to fix so go ahead 👍  :)

2021-10-30 12:20 UTC, negue commented
@all-contributors please add @chiragmahawar7 for code